<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
public function run()
{
DB::table('products')->insert([
//------------------------------------------------------ SPECIALIZED-VEHICALS--------------------------------------------------------
    [
        'product_id' => 'Vehc-Lux-MercedesG6',
        'name' => 'ARMORED Mercedes G63 AMG',
        'price' => '1,099,997.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Mercedes-G63.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-RangeRover',
        'name' => 'ARMORED Range Rover',
        'price' => '499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Range-Rover.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-RollsRoycePhantom',
        'name' => 'ARMORED Rolls Royce Phantom',
        'price' => '1,999,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Rolls-Royce.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-S600Maybach',
        'name' => 'ARMORED Mercedes S600 Maybach',
        'price' => '499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Mercedes-S680-Maybach.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-ToyotaLandCruiser',
        'name' => 'ARMORED Toyota Land Cruiser 300',
        'price' => '399,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Toyota-Land-Cruiser-300.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-LexusLX-600',
        'name' => 'ARMORED Lexus LX-600',
        'price' => '499,997.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Lexus-LX-600.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-ToyotaCamry',
        'name' => 'ARMORED Toyota Camry',
        'price' => '299,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Toyota-Camry.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Lux-CadillacEscalade',
        'name' => 'ARMORED Cadillac Escalade',
        'price' => '2,000,000.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Aksum-Armored-Vehicle-Cadillac-Escalade.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-SWATVehicle',
        'name' => 'ARMORED SWAT Vehicle',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/DS-SWAT.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-6X6',
        'name' => 'ARMORED 6X6',
        'price' => '3,999,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/6X6.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-8SeaterPCV',
        'name' => 'ARMORED 8 Seater PCV',
        'price' => '4,999,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/S.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-12SeaterPCV',
        'name' => 'ARMORED 12 Seater PCV',
        'price' => '5,999,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/V.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-HUMMERAPC',
        'name' => 'ARMORED HUMMER APC',
        'price' => '3,999,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Combat.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-10SeaterPCV',
        'name' => 'ARMORED 10 Seater PCV',
        'price' => '4,499,000.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/FS.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-4SeaterPickup',
        'name' => 'ARMORED 4 Seater Pickup',
        'price' => '2,999,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Comabt-S.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Tac-2SeaterPickup',
        'name' => 'ARMORED 2 Seater Pickup',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/GT.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-ToyotaHilux',
        'name' => 'ARMORED Toyota Hilux',
        'price' => '299,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Toyota-Land-Cruiser-79-CIT-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-GMCSavana',
        'name' => 'ARMORED GMC Savana',
        'price' => '599,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-GMC-Savana-CIT-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-HiluxPickup',
        'name' => 'ARMORED Hilux Pickup',
        'price' => '499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Toyota-Hilux-Double-Cab-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-ToyotaHiAce',
        'name' => 'ARMORED Toyota HiAce',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Toyota-Hiace-CIT-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-MercedesActros',
        'name' => 'ARMORED Mercedes Actros',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Mercedes-Actros-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-AshokLeyland',
        'name' => 'ARMORED Ashok Leyland',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Ashok-Leyland-Falcon-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-HiAceBus',
        'name' => 'ARMORED Hi Ace Bus',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Toyota-Hiace-Commuter-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-LAV-ToyotaCoaster',
        'name' => 'ARMORED Toyota Coaster',
        'price' => '1,499,999.00',
        'image_url' => 'https://aksumarmored.com/wp-content/uploads/2024/04/Akusm-Armored-Vehicles-Toyota-Coaster-thumb.webp',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-MRAP-Cougar',
        'name' => 'ARMORED Cougar',
        'price' => '5,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-MRAP-M-ATV',
        'name' => 'ARMORED M-ATV',
        'price' => '7,999,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-MRAP-Temsah',
        'name' => 'ARMORED Temsah',
        'price' => '6,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-MRAP-ATV',
        'name' => 'ARMORED ATV',
        'price' => '3,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-MRAP-Typhoon',
        'name' => 'ARMORED Typhoon',
        'price' => '9,999,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-MRAP-Kamaz',
        'name' => 'ARMORED Kamaz',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-INKAS',
        'name' => 'ARMORED INKAS',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-Monster',
        'name' => 'ARMORED Monster',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-Alpine',
        'name' => 'ARMORED Alpine',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-Scania',
        'name' => 'ARMORED Scania',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-IAG',
        'name' => 'ARMORED IAG',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-CxxM',
        'name' => 'ARMORED CxxM',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-Telcoline',
        'name' => 'ARMORED Telcoline',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-Riot-TM-170',
        'name' => 'ARMORED TM-170',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-BAESystems',
        'name' => 'ARMORED BAE Systems',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-AAV7',
        'name' => 'ARMORED AAV7',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-Mowag Piranha',
        'name' => 'ARMORED Mowag Piranha',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-Terrex',
        'name' => 'ARMORED Terrex',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-Patria',
        'name' => 'ARMORED Patria',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-Gibbs',
        'name' => 'ARMORED Gibbs',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-AVPT',
        'name' => 'ARMORED AVPT',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Vehc-ACV-Openwater',
        'name' => 'ARMORED Openwater',
        'price' => '4,499,999.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],

//------------------------------------------------------ PROTECTIVE GEARS --------------------------------------------------------
    [
        'product_id' => 'Armor-Head-BallisticHeadGearWithMandible',
        'name' => 'Ballistic Head Gear(With Mandible)',
        'price' => '399.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/ACH%20Combat%20Helmets/Kavro%20ACH-126T/Mandible-Helmet_Right_463_72-dpi-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticHeadGearOliveGreen',
        'name' => 'Ballistic Head Gear(Olive Green)',
        'price' => '399.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/ACH%20Combat%20Helmets/Kavro%20ACH-4/MKH-ACH-4-Product-Left-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticHeadGearBlack',
        'name' => 'Ballistic Head Gear(Black)',
        'price' => '399.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/ACH%20Combat%20Helmets/Kavro%20ACH-126%20T/Kavro%20ACH-126%20T%20(1)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticHeadGearDesertTan',
        'name' => 'Ballistic Head Gear(Desert Tan)',
        'price' => '399.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/ACH%20Combat%20Helmets/Kavro%20ACH-125%20T/Kavro%20ACH-125%20T%20(4)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticVisor',
        'name' => 'Ballistic Visor',
        'price' => '99.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/Accessories/Kavro%20Visors/KAVRO-VD-20-SM_Product_Image-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticGlasses',
        'name' => 'Ballistic Glasses',
        'price' => '299.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/Accessories/Kavro%20Ballistic%20Eyewear/KAVRO-BALLISTIC-EYEWEAR-(3)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticHeadset',
        'name' => 'Ballistic Headset',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/Accessories/Kavro%20Visors/VD-06%20FM/VD-06-FM-(3)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Head-BallisticHeadGearCamouflage',
        'name' => 'Ballistic Head Gear(Camouflage)',
        'price' => '399.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Helmets/ACH%20Combat%20Helmets/Kavro-ACH-114%20T/Kavro-ACH-114T-Left-463x421.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticHeadGearCamouflage',
        'name' => 'Ballistic Head Gear(Camouflage)',
        'price' => '399.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Covert%20Overvests/TAC-II%20(FR)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrierOliveGreen',
        'name' => 'BALLISTIC Plate Carrier(Olive Green)',
        'price' => '499.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Tactical%20Overvests/PLATE%20CARRIER/Plate_Carrier_Side-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrierDesertTan',
        'name' => 'BALLISTIC Plate Carrier(Desert Tan)',
        'price' => '499.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Special%20Purpose%20Vest/EXTRA%20PROTECTION%20VEST/Extra_Portection_Vest-1-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrierBlue',
        'name' => 'BALLISTIC Plate Carrier(Blue)',
        'price' => '499.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Protech%20Overvests/FRONT%20OPENING%20OVER%20VEST/Left_Opening_OverVest-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrier01',
        'name' => 'BALLISTIC Plate Carrier 01',
        'price' => '499.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro-TAC-I-IIA+_mood-shot-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrier02',
        'name' => 'BALLISTIC Plate Carrier 02',
        'price' => '499.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Tactical%20Overvests/FRONT%20OPENING%20VEST/front-image-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrier03',
        'name' => 'BALLISTIC Plate Carrier 03',
        'price' => '499.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Tactical%20Overvests/BODY%20ARMOUR%20WITH%20UPPER%20BODY%20EXO/KAVRO-TAC-I-IIB+_Product-image-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-PltCr-BallisticPlateCarrier04',
        'name' => 'BALLISTIC Plate Carrier 04',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/Kavro%20Ballistic%20Vest/Kavro%20Ballistic%20Vest-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-BallisticBriefcase',
        'name' => 'BALLISTIC Briefcase',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/SOFT%20SHIELD/BALLISTIC%20BRIEFCASE_SPB-I-IA/Ballistic_%20briefcase_SPB_Side-463x463.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-MSH-11',
        'name' => 'MSH-11',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/HARD%20SHIELD/MSH-11-Shield-Side-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-MSH-08',
        'name' => 'MSH-08',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/HARD%20SHIELD/MSH-08-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-MSH-03',
        'name' => 'MSH-03',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/HARD%20SHIELD/HARD%20SHIELDS_MHS-03/HARD-SHIELDS-MSH-03-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-MSH-04A',
        'name' => 'MSH-04A',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/HARD%20SHIELD/HARD%20SHIELDS_MHS-04/HARD%20SHIELDS_MHS-04%20(2)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-MSH-01',
        'name' => 'MSH-01',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/HARD%20SHIELD/HARD%20SHIELDS_MHS-01/HARD%20SHIELDS_MHS-01%20(2)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-MSH-06',
        'name' => 'MSH-06',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/HARD%20SHIELD/HARD%20SHIELDS_MHS-02/HARD%20SHIELDS_MHS-02%20(2)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armor-Shld-BallisticBackpack',
        'name' => 'Ballistic Backpack',
        'price' => '999.00',
        'image_url' => 'https://www.mku.com/image/cache/catalog/SHIELDS/SOFT%20SHIELD/MULTI%20PURPOSE%20SHIELD_SPS-FD-1A/MULTI%20PURPOSE%20SHIELD_SPS-FD-1A%20(4)-228x228.png',
        'created_at' => now(),
        'updated_at' => now(),
    ],

//--------------------------------------------------- ARMOURY -------------------------------------------------------------------------------
    [
        'product_id' => 'Armoury-Pstl-M9BERETTA',
        'name' => 'M9 BERETTA',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/016/854/158/large/renderdock-studio-m9-01.jpg?1553718783',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-COLT1911',
        'name' => 'COLT 1911',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/885/138/large/heavy-machinery-1.jpg?1621560428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-GLOCK17',
        'name' => 'GLOCK 17',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/016/497/851/large/renderdock-studio-glock17-3.jpg?1552392649',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-GLOCK19X',
        'name' => 'GLOCK 19X',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/016/523/154/large/renderdock-studio-glock17-6.jpg?1552487107',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-GLOCK19',
        'name' => 'GLOCK 19',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/073/294/159/large/forge-studios-g19-03.jpg?1709316837',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-GLOCK22',
        'name' => 'GLOCK 22',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/028/004/730/large/carlos-morales-empire-3d-std-glock22-01b.jpg?1593196387',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-GLOCK34',
        'name' => 'GLOCK 34',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/024/091/775/large/shanji-wang-g34-render-2.jpg?1581298047',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-SIGP226',
        'name' => 'SIG SAUER P226',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/041/832/444/large/joris-chambard-p226-camera-1-002.jpg?1632829967',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-SIGP320',
        'name' => 'SIG SAUER P320',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/063/071/727/large/zhabin-yuri-16.jpg?1684659807',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-SIGP365',
        'name' => 'SIG SAUER P365',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/066/363/709/large/igor-antonov-closedcase.jpg?1692723049',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-SIGP322',
        'name' => 'SIG SAUER P322',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/076/860/535/large/sergii-kolesnyk-4-2jpg.jpg?1718014232',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Pstl-SIGP228',
        'name' => 'SIG SAUER P228',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/029/317/812/large/david-oroian-0.jpg?1597158574',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-DOUBLEBARELL',
        'name' => 'DOUBLE BARELL',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/030/503/648/large/ryzin-art-screenshot005.jpg?1600801744',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-BENELI-M4',
        'name' => 'BENELI M4',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/071/149/895/large/artem-n-anton-huleha-benelli-m4-1.jpg?1704558641',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-MOSSBERG-590M',
        'name' => 'MOSSBERG 590M',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/035/815/734/large/amc-ro-studio-render-6.jpg?1615976732',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-REMINGTON-870',
        'name' => 'REMINGTOM 870',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/069/643/793/large/pascual-hernandez-pascualhernandez-remington-870-frontground.jpg?1700641488',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-SIX12',
        'name' => 'SIX12',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/033/584/731/large/alexandru-voinea-studio-1.jpg?1610020632',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-PPK-42',
        'name' => 'PPK-42',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/068/328/445/large/stefan-engdahl-render06.jpg?1697550040',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-BOLTON-BSS',
        'name' => 'Bolton-BSS',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/054/264/885/large/ben-bolton-cs-039.jpg?1664149233',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-PMS-M12',
        'name' => 'PMS M12',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/032/738/658/large/laurentiu-nedelca-pms-m12-006.jpg?1607341003',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-WINCHESTER-1895',
        'name' => 'WINCHESTER 1895',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/016/207/242/large/johann-william-loffler-win1895-3.jpg?1551305389',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-REMINGTON-870',
        'name' => 'REMINGTON 870',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/019/878/478/large/carlos-morales-sm-shotgun-01f.jpg?1565379313',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-DP12',
        'name' => 'DP12',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/015/032/659/large/carlos-morales-cmgs-dp12-00.jpg?1546801438',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Shotgun-FRANCHI-SPAS12',
        'name' => 'FRANCHI SPAS12',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/039/699/066/large/game-weapons-spas12-main-camera.jpg?1626687138',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-WINCHESTER70',
        'name' => 'WINCHESTER 70',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/052/989/163/large/artem-nasyrov-1.jpg?1661170503',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-SAVAGE99',
        'name' => 'SAVAGE 99',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/324/030/large/sheila-hernanz-rifle-11.jpg?1620091356',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-M40A5',
        'name' => 'M40A5',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/052/251/938/large/paddingsons-outsourcing-argocomfortech-5.jpg?1659352972',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-ZASTAVA93',
        'name' => 'ZASTAVA 9.3',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/065/938/295/large/wanis-kazi-03-1-pp.jpg?1691604687',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-HOLLANDHOLLAND',
        'name' => 'HOLLAND & HOLLAND',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/014/185/133/large/joshua-abbott-8.jpg?1542849472',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-HOWA1500',
        'name' => 'HOWA 1500',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/077/515/427/large/ryland-scott-howahr-ue-neutral-renderv01.jpg?1719645588',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    
    [
        'product_id' => 'Armoury-HuntRif-TOZ-34',
        'name' => 'TOZ-34',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/043/728/865/large/luminiferous_slavoch-toz-34-art-2.jpg?1638120893',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-HuntRif-SAUER101',
        'name' => 'SAUER 101 ',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/032/036/716/large/bastien-blanch-sauer-render-4.jpg?1605286506',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-MP-9',
        'name' => 'MP-9',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/075/391/806/large/laurentiun-sow-mp9-006.jpg?1714466659',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-MP-9',
        'name' => 'MP-9',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/075/391/806/large/laurentiun-sow-mp9-006.jpg?1714466659',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-RHN-9',
        'name' => 'RHN-9',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/047/110/807/large/vladislav-babiak-main.jpg?1646820274',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-SMG-45',
        'name' => 'SMG-45',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/077/318/398/large/barkin-eraslan-be-lwrc-9.jpg?1719161863',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-ZJ01',
        'name' => 'ZJ01',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/038/185/817/large/jinyi-zhu-zj01-15.jpg?1622425072',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-P90',
        'name' => 'P90',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/017/502/931/large/jonathan-norden-new-render7.jpg?1556230289',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-TOMMY',
        'name' => 'TOMMY',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/009/780/566/large/linus-scheffel-2.jpg?1520872244',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-ADT-CENTAUR',
        'name' => 'ADT CENTAUR',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/051/088/058/large/sam-white-1.jpg?1656429947',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-LWRC-45',
        'name' => 'LWRC-45',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/014/486/737/large/sviatoslav-chervatiuk-3-1.jpg?1544138779',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-SOW-VECTOR',
        'name' => 'SOW VECTOR',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/078/529/115/large/laurentiun-sow-kv-showcase-014.jpg?1722359554',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-KH9',
        'name' => 'KH9',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/011/742/678/large/ben-armstrong-kh9-alternate-01.jpg?1531173726',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-MAC-10',
        'name' => 'MAC-10',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/032/635/884/large/laurentiu-nedelca-pms-mac-10-v2-003.jpg?1607013910',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SMG-PPK-42',
        'name' => 'PPK-42',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/068/328/445/large/stefan-engdahl-render06.jpg?1697550040',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-PPK-42',
        'name' => 'PPK-42',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/038/298/795/large/emiel-sleegers-gun-cama.jpg?1622709260',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-AR15',
        'name' => 'AR15',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/038/298/795/large/emiel-sleegers-gun-cama.jpg?1622709260',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-SCAR-L',
        'name' => 'SCAR-L',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/063/012/355/large/vladyslav-narozhnyi-4-1.jpg?1684483766',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-AK-74',
        'name' => 'AK-74',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/026/080/777/large/alvaro-fuster-plano01-2.jpg?1587825005',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-OZ-14-GROZA',
        'name' => 'OZ-14 GROZA',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/023/908/824/large/ohle-mathiebe-asd.jpg?1580739750',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-M4',
        'name' => 'M4',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/051/522/759/large/games-artist-side-view-a-main-camera-side-render-fullquality.jpg?1657528828',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-M16A4',
        'name' => 'M16A4',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/007/790/849/large/patrick-benai-screenshot003.jpg?1508520605',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-Type95',
        'name' => 'TYPE-95',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/004/870/763/large/hong-kim-type-95-2.jpg?1486890963',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-SakoRK95TP',
        'name' => 'SAKO RK 95 TP',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/032/564/734/large/mattias-h-mattias-h-sako-rk-95tp-1.jpg?1606821646',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-CZ805BREN',
        'name' => 'CZ 805 BREN A1',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/074/103/752/large/parisa-mohammadsadeghi-untitled-001.jpg?1711233352',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-KAT4',
        'name' => 'KAT-4',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/083/105/797/large/pavel-proskurin-08.jpg?1734780815',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-Saiga12XTS',
        'name' => 'SAIGA 12 XTS',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/009/411/894/large/sergejs-karpovs-saiga12-xts-render-3k-fn1.jpg?1518833428',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-AsltRif-MDR',
        'name' => 'MDR',
        'price' => '22495.00',
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/028/156/669/large/philipp-neumann-side.jpg?1593635121',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-VSSVINTOREZ',
        'name' => 'VSS VINTOREZ',
        'price' => '22495.00',
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/059/693/054/large/martin-abarca-martin-abarca-pavelsniper-02.jpg?1676949462',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-MASFRF2',
        'name' => 'MAS FR F2',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/015/652/031/large/andrei-popescu-render-01.jpg?1549118949',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-SnowOwl',
        'name' => 'SNOW OWL',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/020/398/178/large/jinyi-zhu-asset.jpg?1567617654',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-SpeedModelingM40',
        'name' => 'SPEED MODELING - M40',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/009/881/160/large/airam-hernandez-9.jpg?1521393280',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-RemintonR11',
        'name' => 'REMINTON R11',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/075/542/400/large/vladyslav-narozhnyi-2.jpg?1714828450',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-DVL10M2Urbana',
        'name' => 'DVL-10 M2 URBANA',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/058/540/415/large/ruslan-shumeiko-01-1.jpg?1674412790',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-BarrettMRADMK22',
        'name' => 'THE BARRETT (MRAD) MK22',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/058/455/110/large/dreamerz-lab-1.jpg?1674190194',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-AWM',
        'name' => 'AWM',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/032/985/571/large/ryzin-art-tbrender135.jpg?1608061890',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-MCMILLANTAC-50',
        'name' => 'MCMILLAN TAC-50',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/042/554/882/large/david-avakov-base-right.jpg?1634820191',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-PMSAKRAPOV-S4',
        'name' => 'PMS AKRAPOV S4',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/032/325/342/large/laurentiu-nedelca-pms-akrapov-s4-artstation-001.jpg?1606131100',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-PSG1',
        'name' => 'PSG-1',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/029/739/346/large/zachary-shertz-screenshot176.jpg?1598486375',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-BARRETTM82',
        'name' => 'BARRETT M82',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/009/556/217/large/madushan-wenuranga-m82-01.jpg?1519659409',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-SnprRif-SAKOTRG-42',
        'name' => 'SAKO TRG 42',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/014/728/241/large/peetu-gronholm-trg42.jpg?1545198043',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-RGM-40',
        'name' => 'RGM-40',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/022/975/710/large/stefan-engdahl-rend3.jpg?1577552097',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-TOW',
        'name' => 'TOW',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/082/794/963/large/canoe-render-003-logo.jpg?1733935435',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-M320',
        'name' => 'M320 Grenade Launcher',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/043/651/684/large/james-mainwaring-m320-06.jpg?1637867742',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-FIM-92J',
        'name' => 'FIM 92J Stinger',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/075/667/816/large/oliver-kay-fim92j-05.jpg?1715135077',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-RenegadeX',
        'name' => 'Renegade X',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/001/759/636/large/waqas-iqbal-missilelauncher-01.jpg?1452316612',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-M79',
        'name' => 'M79 Grenade Launcher',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/081/207/922/large/anton-kunstmann-tbrender-camera-3.jpg?1729658616',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-MGL-GRL',
        'name' => 'MGL GRL',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/028/341/786/large/alexandru-voinea-2.jpg?1594196392',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-M203-M4',
        'name' => 'M203 M4',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/060/861/682/large/keal-team-shot-1.jpg?1679481919',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-RPG-LAUNCHER',
        'name' => 'RPG Launcher',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/039/317/318/large/diptiranjan-panigrahi-rpg-5.jpg?1625567421',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-GL06',
        'name' => 'GL06',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/035/073/849/large/jona-pahl-05.jpg?1614032492',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-STEAMPUNK',
        'name' => 'Steampunk',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/024/644/401/large/andrey-nepryahin-screenshot000.jpg?1583087796',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Lnchr-GP-25',
        'name' => 'GP-25',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/039/049/886/large/simon-mercuzot-shot01.jpg?1624815562',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-NSV',
        'name' => 'NSV',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/067/302/959/large/yahli-mendler-full-right-front.jpg?1695055452',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-BRENLMG',
        'name' => 'BREN LMG',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/030/906/233/large/ryzin-art-screenshot004.jpg?1602009117',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-PMSSTAL51',
        'name' => 'PMS STAL-51',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/035/824/176/large/laurentiu-nedelca-pms-stal-51-0017.jpg?1615994607',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-MADEUCE',
        'name' => 'MA DEUCE',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/016/368/578/large/tim-shumaker-3.jpg?1551896691',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-LEWISMG',
        'name' => 'LEWIS MG',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/024/711/350/large/slava-kireev-render8.jpg?1583284348',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-M249SAW',
        'name' => 'M249 SAW',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/080/931/942/large/3dma-studios-saw-pb-01.jpg?1728933712',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-DP28',
        'name' => 'DP 28',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/073/818/901/large/deepak-gollar-dp-28-02.jpg?1710536645',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-Ultimax100',
        'name' => 'ULTIMAX 100 LMG',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/032/692/467/large/kameron-brooks-u100-2.jpg?1607185687',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-M240',
        'name' => 'M-240',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/071/609/751/large/artem-n-anton-huleha-m240d-2.jpg?1705538196',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-Gatling',
        'name' => 'GATLING GUN',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/031/404/822/large/akash-bhatt-gatling-close.jpg?1603523410',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-MinimiMk3',
        'name' => 'MINIMI MK3',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/008/557/367/large/pawin-changkiendee-pawin-changkiendee-minimimk3-7.jpg?1513545241',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-MchnGun-M2Browning',
        'name' => 'M2 BROWNING',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/059/114/297/large/kevuru-games-m2-browning-50cal-02.jpg?1675686492',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-HANDGRENADE',
        'name' => 'HAND GRENADE',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/081/831/355/large/lorenzo-pace-1a.jpg?1731354533',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-FLASHBANG',
        'name' => 'FLASHBANG',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/056/277/092/large/jason-h-m48-fourth-new.jpg?1668861580',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-IED',
        'name' => 'IED',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/052/385/505/large/ted-manske-tnt-001.jpg?1659665510',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-SMOKEGRENADE',
        'name' => 'SMOKE GRENADE',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/056/277/269/large/jason-h-smoke-grenade-diagonal2.jpg?1668861933',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-C4',
        'name' => 'C4',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/064/474/107/large/fan-cheng-tbrender-main-camera.jpg?1688002790',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-ANTITANKMINE',
        'name' => 'ANTI TANK MINE',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/030/533/330/large/damith-galhena-2.jpg?1600884258',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-PINEAPPLEGRENADE',
        'name' => 'PINEAPPLE GRENADE MK2',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/016/076/593/large/declan-sheehan-sub-02.jpg?1550791446',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-M67',
        'name' => 'M67 FRAGMENTATION GRENADE',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/035/152/499/large/vladislav-fjh-gavrilin-shot0.jpg?1614223264',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-M24',
        'name' => 'GERMAN M24 STICK',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/023/096/827/large/marwan-ammar-german-m24-stick-grenade-anti-tank-bundle-wwii-marwan-ammar-04.jpg?1578071224',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-1229STUN',
        'name' => '12/29 STUN',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/034/049/943/large/andre-foster-stun-grenade.jpg?1611255790',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-M26',
        'name' => 'M26 GRENADE',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/063/628/966/large/sidharth-s-grenaderendermain1.jpg?1685987897',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Grnd-MKVGAS',
        'name' => 'MKV GAS',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/049/223/734/large/somdatta-das-grenade-1.jpg?1651997929',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-COMBATKUKRI',
        'name' => 'COMBAT KUKRI',
        'price' => 22495.00,
        'image_url' => 'ttps://cdna.artstation.com/p/marketplace/presentation_assets/001/760/002/large/file.jpg?1654356909',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-KARAMBIT',
        'name' => 'KARAMBIT',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/026/197/952/large/himanshu-sandhu-5k.jpg?1588155323',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-M48KUKRI',
        'name' => 'M48 KUKRI',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/marketplace/presentation_assets/001/170/070/large/file.jpg?1629957542',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-TANTO',
        'name' => 'TANTO',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/002/706/618/large/billy-lundevall-cold-steel-recon-1.jpg?1464796870',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-BUTTERFLY',
        'name' => 'BUTTERFLY KNIFE',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/034/982/294/large/sean-o-brien-renders1.jpg?1613765173',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-PUSHDAGGER',
        'name' => 'PUSH DAGGER',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/077/133/282/large/sergey-nikulshin-sergey-nikulshin-2.jpg?1718686307',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-MACHETE',
        'name' => 'MACHETE',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/031/660/680/large/kirill-sp-8-5.jpg?1604253408',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-FEATHERBLADE',
        'name' => 'FEATHER BLADE',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/025/184/491/large/brx-boyles-featherblade-01.jpg?1584938761',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-MODERNGYUTO',
        'name' => 'MODERN GYUTO',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/079/003/761/large/james-bolton-moderngyutorendersfinal-4.jpg?1723679978',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-MOONSPLINTER',
        'name' => 'MOON SPLINTER',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/044/531/558/large/mike-kennedy-moonsplinter-2021-1.jpg?1640278852',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-HUNTINGKNIFE',
        'name' => 'HUNTING KNIFE',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/072/596/515/large/wanis-kazi-2.jpg?1707760452',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Armoury-Knife-TOMHAWK',
        'name' => 'TOMHAWK',
        'price' => 22495.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/072/895/272/large/reviron-img-9.jpg?1708449581',
        'created_at' => now(),
        'updated_at' => now(),
    ],
//---------------------------------------------------- OPTICS -------------------------------------------------------------------------------------------
    [
        'product_id' => 'Optics-Scope-HolosunElite',
        'name' => 'HOLOSUN ELITE',
        'price' => 22495.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/058/956/651/large/vladislav-kravchenko-5.jpg?1675317718',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-M110k1',
        'name' => 'M110k1',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/022/265/741/large/linus-scheffel-schmidt-benderoptic1.jpg?1574764917',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-RedDot',
        'name' => 'Red Dot',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/036/668/529/large/mustafa-majeed-3.jpg?1618306315',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-LeupoldMarkIV',
        'name' => 'Leupold Mark IV',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/044/501/097/large/nestor-sarmiento-prueba-main-camera-002.jpg?1640187426',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-BushnellTRS25',
        'name' => 'Bushnell TRS-25',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/074/822/599/large/stephen-mok-c-02-c-c-04-p05-vanity-wide.jpg?1713060893',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-AimpointMicroT2',
        'name' => 'Aimpoint Micro T2',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/076/165/283/large/dmytro-bushylov-pose-1.jpg?1716328861',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-TrijiconACOG',
        'name' => 'Trijicon ACOG',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/071/756/895/large/carlos-morales-empire-3d-std-acog-013.jpg?17058823063',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Scope-S9LPVO',
        'name' => 'S9 LPVO',
        'price' => 30000.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/058/137/986/large/hector-cervantes-asset.jpg?1673466449',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-NVG-PanoramicNVG',
        'name' => 'Panoramic NVG',
        'price' => 30000.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/036/341/792/large/bucket-hex-tbrender001-shot-1-fullquality.jpg?1617390227',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-NVG-MonoTubeNVG',
        'name' => 'Mono-Tube NVG',
        'price' => 70000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/065/363/617/large/georgiy-kiselev-1pn138-render002-test-6.jpg?1690201799',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-NVG-MinieWilcoxG29',
        'name' => 'Minie Wilcox G29',
        'price' => 70000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/077/116/711/large/ilya-rukhlyada-1-viewport-019.jpg?1718642929',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-NVG-WilcoxG29',
        'name' => 'Wilcox G29',
        'price' => 50000.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/077/116/672/large/ilya-rukhlyada-1-viewport-012.jpg?1718642871',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-NVG-FuturisticNVG',
        'name' => 'Futuristic NVG',
        'price' => 30000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/011/362/481/large/nicholas-lim-helmet-composite.jpg?1529196400',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-NVG-DualTubeWithMount',
        'name' => 'Dual-Tube With Mount',
        'price' => 55000.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/070/409/944/large/antoine-george-explode-01.jpg?1702471561',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Laser-DBAL-D2',
        'name' => 'DBAL-D2',
        'price' => 55000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/037/912/099/large/roman-kozak-shot-1.jpg?1621634549',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Laser-MAWL-C1',
        'name' => 'MAWL-C1',
        'price' => 55000.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/037/383/280/large/benedict-burns-perst-4-artstation-presentation-3.jpg?1620232422',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Laser-PEQ-15',
        'name' => 'PEQ-15',
        'price' => 55000.00,
        'image_url' => 'https://cdna.artstation.com/p/assets/images/images/043/925/382/large/wenwen-ar15keys-4-17.jpg?1638633290',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'product_id' => 'Optics-Laser-LA5',
        'name' => 'LA5',
        'price' => 55000.00,
        'image_url' => 'https://cdnb.artstation.com/p/assets/images/images/015/471/275/large/anton-pismennyy-anton-pismennyy-lcu-13.jpg?1548454625',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    
]);
}
}
